parameters:

    ongr_task_messenger.connection_factory.class: ONGR\TaskMessengerBundle\Publishers\ConnectionFactory
    ongr_task_messenger.task_publisher.class: ONGR\TaskMessengerBundle\Service\TaskPublisher

    ongr_task_messenger.publisher.amqp.class: ONGR\TaskMessengerBundle\Publishers\AMQPPublisher
    ongr_task_messenger.publisher.beanstalkd.class: ONGR\TaskMessengerBundle\Publishers\BeanstalkdPublisher

    ongr_task_messenger.sync_task_complete_listener.class: ONGR\TaskMessengerBundle\Service\SyncTasksListener

    ongr_task_messenger.logger.class: Symfony\Component\HttpKernel\Log\NullLogger
services:
    ongr_task_messenger.sync_task_complete_listener:
        class: %ongr_task_messenger.sync_task_complete_listener.class%
        tags:
            - { name: kernel.event_listener, event: ongr_connections.sync_task_complete, method: handleEvent }

    ongr_task_messenger_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [ongrTaskMessenger]
        calls:
            - [pushHandler, [@ongr_task_messenger_logger_handler]]

    ongr_task_messenger_logger_handler:
        class: Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/%kernel.environment%_task_messenger.log, %ongr_connections.log_level%]
